name: Java Spring Boot CI/CD Pipeline

# Start process when have an actions on main and dev branch
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Pull source code from GitHub Repo come to Runner
    - name: Checkout source code
      uses: actions/checkout@v4

    # 2. Installation JDK
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 3. Grant execution permission for mvnw
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    # 4. Run complication and tests for all code (if there are errors, merging will be blocked)
    - name: Build and Test with Maven
      run: ./mvnw clean verify
